### ISSUE TITLE
Does the migrate of RTC stream bring along the snaphots as tags in Git ? 

### ISSUE THREAD

**Issue by keithvb1** [rtcTo/rtc2git#100]
I am migrating a RTC stream which has 12 snapshots . I give it the initial baseline in the rtc2git config.ini file  and I identified "history" change sets to migrate . If I need to debug a problem at a specific snapshot level, in RTC , I can create a workspace with the snapshot level.  Will I be able to do the same in git as a result of the migrate performed when using rtc2git tool ?
I appreciate you assistance !

**Comment by WtfJoke** [comment]
Hi there

Sadly the migration of rtc snapshots in git tags is not supported (see #63 ). The problem is that additional requests I would need to make in order to identify them (if its even possible on command line only) and this would take too much time for migration.

But you can use our other project rtc2gitcli (see [comment on #63 ](https://github.com/rtcTo/rtc2git/issues/63#issuecomment-194885809)), which supports that.

If you have any issues with it, please let us know by opening an issue there. :)
In case it didnt answered your question, feel free to reopen this issue.
