### ISSUE TITLE
Issue in Set new Flowtargets

### ISSUE THREAD

**Issue by nareshAlac** [rtcTo/rtc2git#105]
Hi,

I am trying a sample code for migration of rtc repo to my local git repo. i am able to create empty git and push the streams of rtc into git repository. But i am unable to access the commit message. I am stuck with the below error:  

Problem running 'set flowtarget':
The specified value for the --current option is not valid. Try 'scm help set flowtarget' for more information

**Comment by WtfJoke** [comment]
Hi there,

Looks like you cant set your flow target of your workspace for some reason. Sounds like the streamuuid is invalid.

Can you try executing following command in your console:
lscm set flowtarget -r REPO WORKSPACENAME --default --current STREAMUUID

Please post your results here

**Comment by tokra** [comment]
i tried, but:
![image](https://cloud.githubusercontent.com/assets/2188084/20490618/e13ab866-b00e-11e6-9230-49587aa9a028.png)

**Comment by gpflaum** [comment]
The problem is that RTC 6 changed the options for "set flowtarget". [This line](https://github.com/rtcTo/rtc2git/blob/develop/rtcFunctions.py#L80) can be changed to `--default b --current b` to work with RTC 6, but that won't work on RTC 5.

Some possible ways to handle areas where RTC 5 and RTC 6 behave differently:
- Start a separate branch of rtc2git for RTC 5.
- Specify the RTC version in config.ini, and use the appropriate command at run time. Default to RTC 6.
- Dynamically determine the RTC version, by checking the output of `scm version` . That doesn't show the RTC version, but the com.ibm.team.filesystem.cli.client version could be used:
  - 3.2.600.v20151027_1911 is RTC 6.0.1
  - 3.2.400.v20141016_0123 is RTC 5.0.2
