### ISSUE TITLE
"<No comment>" comment is translated to "<No comment to"

### ISSUE THREAD

**Issue by jacobilsoe** [rtcTo/rtc2git#65]
It seems that > -> --> are all replaced with to when translating the commit message from Rtc to Git. Is this really necessary? I don't see why > should be disallowed in a git commit message.

**Comment by ohumbel** [comment]
This is due to method `replacegitcreatingfilesymbol` in `gitFunctions.py`.
I think it has to do with the way we execute git commands on the command line.
Maybe @WtfJoke remembers the details?

**Comment by WtfJoke** [comment]
@ohumbel is correct.

I barely remembered. However after some testing and viewing the commits I think I was able to...

If you dont quote the git commit message and it contains ">", git will create a file...

Example:
"git commit -m Fixed some details -> please check User Story 3133"
This will create a file named "please"

Probably its not necessary anymore because I quote the message on commit.
What worries me a bit is that during the time I implemented it, I woted the commit-message already (see https://github.com/rtcTo/rtc2git/commit/24ae5e6954609032ad93316c739fd871a39b315b). So there shouldnt be an issue....


I am going to write some tests...

**Comment by WtfJoke** [comment]
Tests were positive. It looks like it was more a precaution thing.
But would be glad if one of you guys ( @ohumbel / @jacobilsoe ) could test if there are no files get created in the root directory of the migration. 

I will close this issue after I got feedback from one of you guys.

**Comment by jacobilsoe** [comment]
The comments in my migration run looks correct now. Thanks.

**Comment by WtfJoke** [comment]
Thanks for feedback. I guess no files has been created by the git commands. Therefore close
