### ISSUE TITLE
What to do about conflicts

### ISSUE THREAD

**Issue by jphx** [rtcTo/rtc2git#90]
I have a question.  I don't understand how conflicts occur when examining the RTC history and what I can do about them.

I've been trying to convert an RTC stream and even took the time to gather the history of each component using Eclipse. as recommended.  But the conversion still fails due to conflicts.  I increased the MaxChangeSetsToAcceptTogether setting to 1000, in case that would help.  My conversion fails after creating about 70 git commits, however, with the message "Change wasnt succesfully accepted into workspace", followed by a listing of 595 change sets.

What does this error really mean, and more importantly, what can I do about it?  I'm not sure where to go from here.

**Comment by WtfJoke** [comment]
Hi jphx,

First of all, sorry for the late response.

As far as I can tell you did everything correct. Youre asking about what this error really means.. For some reason, the changes cannot accepted into the corresponding workspace. This error is thrown by the rtc commandline, sometimes a error-message gets displayed by the cli (but sadly not everytime), which describes the error in a detailed way (for example cant get accepted because of a conflict). You could check if there is such an detailed error message by the rtc-cli.

Also a teammember had an idea, which he thinks will solve your problem. I will try to get this fix on the develop branch as fast as possible and then you can test it.

_Background: Often rtc creates merge changesets (for some unknown reasons) when accepting changesets. This could end up in some uncomfortable situation like yours. However there is an option/argument which you can pass to avoid that. I wasnt aware of this option so far... The upcoming pull-request and merge will add that automatically._

I keep you updated.

**Comment by WtfJoke** [comment]
@jphx  Can you please test your migration by using the latest code from develop branch and tell me if it solved your problem or not?

Thank you very much :smile: :+1:

**Comment by jphx** [comment]
I started the conversion over this morning, and it's still running.  It's at 2477 commits to git so far, so it's gotten a lot farther than it's ever gotten before.  The change you made definitely seems to be helping.  Thanks!  I'll let you know the final status.

**Comment by ohumbel** [comment]
@jphx glad to hear!
Thanks for the feedback, and let's hope your migration finishes.

**Comment by WtfJoke** [comment]
Cool to hear that, thank you for the fast feedback :smiley:
Im curious about your final result.  :four_leaf_clover:

**Comment by jphx** [comment]
It took about 10 hours, but the conversion completed successfully.  That's terrific!  Thanks for your help, and for this utility.

**Comment by WtfJoke** [comment]
Wohoo, thats great to hear :+1: :tada: :confetti_ball: :tada::tada:

Thank you!

I'll close it here. If there is something regarding this issue, feel free to reopen it :)
